# Generated by Django 5.0.6 on 2024-06-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('data_ur', models.DateField()),
                ('plec', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('wychowawca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.nauczyciel')),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('data_ur', models.DateField()),
                ('plec', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('adres_zam', models.CharField(max_length=255)),
                ('klasa_F', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.klasa')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.FloatField()),
                ('nazwa', models.CharField(max_length=50)),
                ('data_wyst', models.DateField(max_length=255)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.nauczyciel')),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.przedmiot')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.uczen')),
            ],
        ),
    ]
