# Generated by Django 5.0.6 on 2024-06-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_klasa_f_uczen_klasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczen',
            name='klasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.klasa'),
        ),
    ]
