# Generated by Django 5.0.6 on 2024-06-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_remove_ocena_nauczyciel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
    ]
