# Generated by Django 5.0.6 on 2024-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_sclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnect',
            name='other_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
